# Generated by Django 5.1 on 2024-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('senha', models.CharField(max_length=128)),
                ('confirmar_senha', models.CharField(max_length=128)),
            ],
        ),
    ]
