# Generated by Django 5.1 on 2024-09-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abnt_model', '0002_simple_tcc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simple_tcc',
            old_name='keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='simple_tcc',
            old_name='problematização',
            new_name='problematizacao',
        ),
    ]
