# Generated by Django 5.1 on 2024-09-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnt_model', '0003_rename_keyword_simple_tcc_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simple_tcc',
            name='nome_do_arquivo',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='simple_tcc',
            name='url_imagem',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
    ]
