# Generated by Django 5.1 on 2024-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abnt_model', '0004_alter_simple_tcc_nome_do_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple_tcc',
            name='local',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
