# Generated by Django 5.1 on 2024-09-16 03:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abnt_model', '0005_simple_tcc_local'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Simple_TCC',
            new_name='Ensaio',
        ),
    ]
